<template>
  <view class="page">
    <view class="head row"><view><text class="eyebrow">{{ labels.eyebrow }}</text><text class="title">{{ labels.title }}</text><text class="subtitle">{{ labels.subtitle }}</text></view><view class="avatar">绿</view></view>
    <view class="hero card"><view><text class="hero-label">{{ labels.reduction }}</text><text class="hero-value">{{ overview.reduction }} <text class="unit">kg CO2</text></text><text class="hero-note">{{ labels.reductionNote }}</text></view><text class="hero-icon">♧</text></view>
    <view class="grid-2"><view class="metric"><text class="metric-label">{{ labels.products }}</text><text class="metric-value">{{ overview.productCount }}</text><text class="muted">件</text></view><view class="metric"><text class="metric-label">{{ labels.exchange }}</text><text class="metric-value">{{ overview.exchangeCount }}</text><text class="muted">次</text></view></view>
    <view class="section-title"><text>{{ labels.pendingTitle }}</text><text class="muted">{{ pendingTotal }} 项</text></view>
    <view class="pending card"><view class="pending-row" @tap="open('/pages/enterprise/low-stock')"><text>{{ labels.lowStock }}</text><text>{{ pending.lowStock }} 项 ›</text></view><view class="pending-row" @tap="open('/pages/enterprise/orders')"><text>{{ labels.orders }}</text><text>{{ pending.orders }} 项 ›</text></view></view>
    <view class="section-title"><text>{{ labels.overview }}</text><text class="muted" @tap="open('/pages/enterprise/reports')">查看详情 ›</text></view>
    <view class="overview card"><view><text class="overview-value">{{ overview.exchangeCount }}</text><text class="muted">本月兑换</text></view><view><text class="overview-value">{{ overview.lowStock }}</text><text class="muted">库存预警</text></view><view><text class="overview-value">{{ overview.reduction }}</text><text class="muted">预计减碳 kg</text></view></view>
    <view class="ai-card" @tap="open('/pages/personal/ai')"><text class="ai-icon">✦</text><view><text class="ai-title">碳宝AI</text><text class="muted">咨询商品、活动和企业碳运营问题</text></view><text class="arrow">›</text></view>
    <BottomNav role="enterprise" active="home" />
  </view>
</template>
<script>
import BottomNav from '../../components/BottomNav.vue'
import { callCloud } from '../../common/cloud.js'
const labels = { eyebrow: '\u4f01\u4e1a / \u7eff\u8272\u54c1\u724c\u7aef', title: '\u7eff\u8272\u8fd0\u8425\u4e2d\u5fc3', subtitle: '\u8ba9\u7eff\u8272\u5408\u4f5c\u6c89\u6dc0\u4e3a\u53ef\u91cf\u5316\u4ef7\u503c', reduction: '\u5546\u54c1\u9884\u8ba1\u51cf\u78b3\u91cf', reductionNote: '\u6765\u81ea\u5f53\u524d\u5728\u552e\u5546\u54c1\u5e93\u5b58', products: '\u5728\u552e\u5546\u54c1', exchange: '\u672c\u6708\u5151\u6362', pendingTitle: '\u5f85\u5904\u7406\u4e8b\u9879', certification: '\u4f01\u4e1a\u8ba4\u8bc1\u5ba1\u6838', lowStock: '\u4f4e\u5e93\u5b58\u5546\u54c1', orders: '\u5f85\u5904\u7406\u5151\u6362\u8ba2\u5355', overview: '\u5546\u54c1\u8fd0\u8425\u6982\u89c8' }
export default { components: { BottomNav }, data() { return { labels, pending: { certification: 0, lowStock: 0, lowStockProducts: [], orders: 0 }, overview: { productCount: 0, exchangeCount: 0, reduction: 0, lowStock: 0 } } }, computed: { pendingTotal() { return this.pending.lowStock + this.pending.orders } }, onShow() { const enterpriseId = uni.getStorageSync('user_session')?.id || 'enterprise_demo'; callCloud('enterprise-overview', { enterpriseId }).then(result => { this.pending = { ...this.pending, ...(result.pending || {}) }; this.overview = result.overview || this.overview }).catch(() => {}) }, methods: { open(url) { uni.navigateTo({ url }) } } }
</script>
<style scoped>
.low-stock-row{display:flex;align-items:center;gap:16rpx;padding:16rpx 0;border-bottom:1rpx solid #edf1ef}.low-stock-row image{width:72rpx;height:72rpx;border-radius:12rpx}.low-stock-row view{flex:1}.low-stock-name{display:block;color:#53615f;font-size:23rpx}.low-stock-warning{color:#c44b42;font-size:20rpx}
</style>
<style lang="scss">@import '../../common/portal.scss';.avatar{display:flex;align-items:center;justify-content:center;width:72rpx;height:72rpx;border-radius:50%;background:#d6e6e3;color:#006d37}.hero{display:flex;align-items:center;justify-content:space-between;background:linear-gradient(135deg,#e4f4eb,#fff)}.hero-label,.metric-label{display:block;color:#53615f;font-size:23rpx}.hero-value{display:block;margin-top:12rpx;color:#006d37;font-size:52rpx;font-weight:700}.unit{font-size:24rpx;font-weight:400}.hero-note{display:block;margin-top:10rpx;color:#347c55;font-size:22rpx}.hero-icon{display:flex;align-items:center;justify-content:center;width:90rpx;height:90rpx;border-radius:50%;background:#fff;color:#006d37;font-size:50rpx}.metric-value{display:block;margin-top:10rpx;color:#006d37;font-size:40rpx;font-weight:700}.pending,.overview{padding:0 26rpx}.pending-row{display:flex;justify-content:space-between;padding:25rpx 0;border-bottom:1rpx solid #edf1ef;color:#53615f;font-size:24rpx}.pending-row:last-child{border:0}.pending-row text:last-child{color:#398052}.overview{display:flex;justify-content:space-around;padding:28rpx 10rpx;text-align:center}.overview-value{display:block;color:#006d37;font-size:34rpx;font-weight:700}.ai-card{display:flex;align-items:center;margin-top:24rpx;padding:26rpx;border-radius:26rpx;background:#d6e6e3}.ai-icon{margin-right:18rpx;color:#006d37;font-size:38rpx}.ai-card view{flex:1}.ai-title{display:block;color:#00391a;font-size:29rpx;font-weight:700}.arrow{color:#006d37;font-size:42rpx}</style>
