<template><view class="page checkin-page"><view class="back" @tap="back">‹</view><view class="head-title">{{ challenge.title }}</view><view class="task-intro card"><view class="task-icon">{{ challenge.icon }}</view><view><text class="task-title">今日打卡任务</text><text class="muted">上传符合要求的照片，提交后等待审核。</text></view></view><text class="label">实景照片 <text class="required">*</text></text><view class="upload-box" @tap="chooseProof"><image v-if="proof" :src="proof" mode="aspectFill"/><view v-else><text class="upload-icon">＋</text><text class="upload-title">上传实景照片</text><text class="muted">要求：{{ challenge.proof }}</text></view></view><text class="label">打卡说明</text><textarea class="input note" placeholder="输入打卡说明..." v-model="remark"/><view class="primary-btn submit" @tap="submit">✓ 提交打卡</view></view></template>
<script>
import { toast } from '../../common/mock.js'
const challenges={
  'meal-7':{title:'连续7天光盘行动',icon:'🍽',proof:'餐后餐盘照片',target:7},
  'bike-5':{title:'连续5天骑行',icon:'🚲',proof:'骑行现场照片',target:5},
  'cup-3':{title:'连续3天自带水杯',icon:'🥤',proof:'当天水杯照片',target:3},
  'sort-3':{title:'垃圾分类达人',icon:'♻',proof:'分类投放照片',target:3},
  'power-5':{title:'节约用电挑战',icon:'💡',proof:'关闭电器现场照片',target:5}
}
export default { data(){return{challenge:{title:'低碳挑战',icon:'🌱',proof:'相关实景照片',target:1},id:'',proof:'',remark:''}}, onLoad(options){this.id=options.id||'meal-7';this.challenge=challenges[this.id]||this.challenge}, methods:{back(){uni.navigateBack()},chooseProof(){uni.chooseImage({count:1,sizeType:['compressed'],sourceType:['album','camera'],success:result=>{this.proof=result.tempFilePaths[0]}})},submit(){if(!this.proof)return toast('请先上传实景照片');const session=uni.getStorageSync('user_session')||{};const key='challenge_states_'+(session.id||session.username||'guest');const states=uni.getStorageSync(key)||{};const old=states[this.id]||{progress:0,status:'in_progress'};const progress=Math.min((old.progress||0)+1,this.challenge.target);states[this.id]={...old,progress,status:progress>=this.challenge.target?'completed':'in_progress',lastSubmitAt:Date.now(),reviewStatus:'pending'};uni.setStorageSync(key,states);toast(progress>=this.challenge.target?'挑战已完成，等待审核':'打卡已提交，等待审核');setTimeout(()=>uni.navigateBack(),500)}}}
</script>
<style lang="scss">@import '../../common/portal.scss';.checkin-page{padding-top:18rpx}.back{display:flex;align-items:center;width:68rpx;height:68rpx;font-size:58rpx}.head-title{text-align:center;margin-top:-64rpx;color:#006d37;font-size:38rpx;font-weight:700}.task-intro{display:flex;align-items:center;margin-top:66rpx}.task-icon{display:flex;align-items:center;justify-content:center;width:82rpx;height:82rpx;margin-right:22rpx;border-radius:50%;background:#e5f4e9;color:#27ae60;font-size:38rpx}.task-title{display:block;margin-bottom:10rpx;color:#181c1c;font-size:30rpx;font-weight:700}.label{display:block;margin:36rpx 8rpx 14rpx;color:#53615f;font-size:25rpx}.required{color:#ba1a1a}.upload-box{display:flex;align-items:center;justify-content:center;height:360rpx;border:4rpx dashed #b8dfc5;border-radius:22rpx;background:#fff;text-align:center}.upload-box image{width:100%;height:100%;border-radius:18rpx}.upload-icon,.upload-title,.upload-box .muted{display:block}.upload-icon{color:#56b36c;font-size:56rpx}.upload-title{margin-top:10rpx;color:#56b36c;font-size:28rpx}.note{height:210rpx;margin-top:0}.submit{height:100rpx;margin-top:190rpx;border-radius:52rpx;font-size:32rpx}</style>
