<template>
  <view class="page"><view class="back" @tap="back">‹</view><view class="head"><text class="title">个人信息</text><text class="subtitle">完善学校信息和收货信息，方便参与活动及兑换商品。</text></view><view class="form card"><text class="label">学校</text><input class="input" placeholder="例如：安徽理工大学" v-model="form.schoolName"/><text class="label">学院</text><input class="input" placeholder="例如：计算机科学与工程学院" v-model="form.college"/><text class="label">专业</text><input class="input" placeholder="例如：软件工程" v-model="form.major"/><text class="label">班级</text><input class="input" placeholder="例如：软件工程24-1班" v-model="form.className"/><text class="label">收货人</text><input class="input" placeholder="请输入收货人姓名" v-model="form.receiverName"/><text class="label">联系电话</text><input class="input" type="number" placeholder="请输入联系电话" v-model="form.phone"/><text class="label">收货地址</text><textarea class="textarea" placeholder="请输入详细收货地址" v-model="form.address"/></view><view class="primary-btn save" @tap="save">保存个人信息</view></view>
</template>
<script>
import { callCloud } from '../../common/cloud.js'
import { toast } from '../../common/mock.js'
export default { data() { return { form: { schoolName: '', college: '', major: '', className: '', receiverName: '', phone: '', address: '' } } }, onShow() { const user = uni.getStorageSync('user_session') || {}; this.form = { schoolName: uni.getStorageSync('user_school_name') || '', college: uni.getStorageSync('user_college') || '', major: uni.getStorageSync('user_major') || '', className: uni.getStorageSync('user_class_name') || '', receiverName: user.receiverName || uni.getStorageSync('user_receiver_name') || '', phone: user.phone || uni.getStorageSync('user_phone') || '', address: user.address || uni.getStorageSync('user_address') || '' } }, methods: { back() { uni.navigateBack() }, async save() { if (!this.form.schoolName || !this.form.college || !this.form.major || !this.form.className || !this.form.receiverName || !this.form.phone || !this.form.address) return toast('请完善个人和收货信息'); const user = uni.getStorageSync('user_session') || {}; try { await callCloud('user-school-update', { userId: user.id, schoolId: uni.getStorageSync('user_school_id') || 'school_001', schoolName: this.form.schoolName, college: this.form.college, major: this.form.major, className: this.form.className, receiverName: this.form.receiverName, phone: this.form.phone, address: this.form.address }); Object.keys(this.form).forEach(key => uni.setStorageSync(`user_${key}`, this.form[key])); uni.setStorageSync('user_session', { ...user, ...this.form }); toast('个人信息已保存'); setTimeout(() => uni.navigateBack(), 500) } catch (error) { toast(error.message || '保存失败') } } } }
</script>
<style lang="scss">@import '../../common/portal.scss';.back{font-size:58rpx}.head{padding:28rpx 4rpx}.head .title{font-size:50rpx}.form{padding:28rpx}.label{display:block;margin:22rpx 0 10rpx;color:#53615f;font-size:24rpx}.input,.textarea{width:100%;padding:0 24rpx;border-radius:20rpx;background:#f1f4f3;box-sizing:border-box}.input{height:92rpx;line-height:92rpx}.textarea{height:180rpx;padding-top:24rpx}.save{margin-top:28rpx;height:96rpx;border-radius:48rpx}</style>
