<template>
  <view class="page campus-profile"><view class="brand"><view class="leaf">✦</view><text class="brand-title">校园管理员个人信息</text></view><text class="hint">校园管理员账号由后台统一导入和启用。</text><view class="card info"><view><text class="label">账号状态</text><text class="approved">后台已启用</text></view><view><text class="label">登录账号</text><text>{{ user.username || '未设置' }}</text></view><view><text class="label">学校名称</text><text>{{ user.schoolName || '未设置' }}</text></view><view><text class="label">管理员姓名</text><text>{{ user.campusAdminName || user.nickname || '未设置' }}</text></view><view><text class="label">管理员工号</text><text>{{ user.campusWorkNo || '未设置' }}</text></view><view class="action-row" @tap="changePassword"><text>修改密码</text><text class="chevron">›</text></view></view><BottomNav role="campus" active="profile" /></view>
</template>
<script>
import BottomNav from '../../components/BottomNav.vue'
import { callCloud } from '../../common/cloud.js'
import { toast } from '../../common/mock.js'
export default { components: { BottomNav }, data() { return { user: {} } }, onShow() { this.user = uni.getStorageSync('user_session') || {} }, methods: { changePassword() { uni.showModal({ title: '验证当前密码', editable: true, placeholderText: '请输入当前密码', success: first => { if (!first.confirm || !first.content) return; uni.showModal({ title: '设置新密码', editable: true, placeholderText: '请输入新密码（至少6位）', success: async second => { if (!second.confirm || !second.content) return; try { await callCloud('campus-password-update', { userId: this.user.id, oldPassword: first.content, newPassword: second.content }); toast('密码修改成功') } catch (error) { toast(error.message || '密码修改失败') } } }) } }) } } }
</script>
<style lang="scss">@import '../../common/portal.scss';.campus-profile{padding:24rpx}.brand{display:flex;align-items:center;padding:18rpx 0 30rpx;border-bottom:1rpx solid #e8efeb}.leaf{margin-right:14rpx;color:#277a43;font-size:42rpx}.brand-title{color:#277a43;font-size:36rpx;font-weight:700}.hint{display:block;margin:24rpx 4rpx;color:#7d8a82;font-size:24rpx}.card{padding:26rpx;border-radius:28rpx;background:#fff;box-shadow:0 8rpx 24rpx rgba(25,90,55,.06)}.info view{display:flex;justify-content:space-between;padding:24rpx 0;border-bottom:1rpx solid #edf1ee;font-size:27rpx}.info view:last-child{border-bottom:0}.label{color:#59675f}.approved{color:#28743d;font-weight:700}.action-row{color:#277a43;font-weight:700}.chevron{font-size:38rpx}</style>
